=== jeanschmidt/staticsite/xsd/rb.xsd
<?xml version="1.0" encoding="utf-8" ?>
<!--
@Versao: 1.0
@Data: 2014-06-01
  -->
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.rastreabilidadebrasil.com.br/RBTypes" xmlns:rb="http://www.rastreabilidadebrasil.com.br/RBTypes"
	elementFormDefault="qualified" version="1.0">
	<simpleType name="CNPJ">
		<annotation>
				<documentation>Sem pontos e tracos</documentation>
			</annotation>
			<restriction base="string">
					<pattern value="\d{14}" />
					<length value="14" />
			</restriction>
	</simpleType>
	<simpleType name="Codigo">
			<restriction base="int">
			</restriction>
	</simpleType>
	<simpleType name="RegistroAnvisa">
			<restriction base="string">
					<pattern value="[1]{1}[0-9]{12}"/>
					<length value="13"/>
			</restriction>
	</simpleType>
	<simpleType name="GTIN">
			<restriction base="string">
					<pattern value="[0-9]{8}|[0-9]{12}|[0-9]{13}|[0-9]{14}"/>
			</restriction>
	</simpleType>
	<simpleType name="DataValidade">
		<annotation>
			<documentation>Formato: MMAA</documentation>
		</annotation>
			<restriction base="string">
					<pattern value="(([0]{1}[1-9]{1})|([1]{1}[0-2]{1}))\d{2}"></pattern>
					<length value="4"/>
			</restriction>
	</simpleType>
	<simpleType name="Lote">
			<restriction base="string">
					<whiteSpace value="collapse" />
					<minLength value="1" />
					<maxLength value="20" />
			</restriction>
	</simpleType>
	<simpleType name="Serial">
			<restriction base="string">
					<pattern value="[0-9]{13}" />
					<length value="13" />
			</restriction>
	</simpleType>
	<simpleType name="Info">
			<restriction base="string">
					<minLength value="0" />
					<maxLength value="512" />
			</restriction>
	</simpleType>
	<simpleType name="InfoCliente">
			<restriction base="string">
					<minLength value="0" />
					<maxLength value="512" />
			</restriction>
	</simpleType>
    <element name="Eventos" type="rb:eventosType">
	    <unique name="unique-id">
	    	<selector xpath="*"/>
	    	<field xpath="@id"/>
	   	</unique>
    </element>
  <complexType name="ocorrenciaType">
    <sequence>
      <element type="string" name="IdItem"/>
      <element type="rb:Codigo" name="Codigo"/>
      <element type="string" name="NotaFiscal"  minOccurs="0"/>
      <element type="integer" name="Timestamp"/>
      <element type="integer" name="Timezone"/>
      <element type="rb:Info" name="Info" minOccurs="0"/>
      <element type="rb:InfoCliente" name="InfoCliente" minOccurs="0"/>
    </sequence>
		<attribute type="string" name="id" use="required"/>
  </complexType>
  <complexType name="childrenType">
    <sequence>
      <element type="string"  maxOccurs="unbounded" minOccurs="1" name="IdItem"/>
    </sequence>
  </complexType>
  <complexType name="itemType">
    <sequence>
      <element type="rb:GTIN" name="GTIN"/>
      <element type="rb:RegistroAnvisa" name="RegistroAnvisa"/>
      <element type="rb:Serial" name="Serial"/>
      <element type="rb:Lote" name="Lote"/>
      <element type="rb:DataValidade" name="DataValidade"/>
    </sequence>
  </complexType>
  <complexType name="cancelamentoType">
    <sequence>
      <element type="string" name="IdItem"/>
      <element type="rb:Codigo" name="Codigo"/>
      <element type="string" name="idOcorrenciaCancelada" minOccurs="0"/><!-- caso nao seja informado, sera cancelado o ultimo evento com este codigo -->
      <element type="integer" name="Timestamp"/>
      <element type="integer" name="Timezone"/>
      <element type="rb:Info" name="Info" minOccurs="0"/>
      <element type="rb:InfoCliente" name="InfoCliente" minOccurs="0"/>
    </sequence>
		<attribute type="string" name="id" use="required"/>
  </complexType>
  <complexType name="movimentacaoType">
    <sequence>
      <element type="string" name="IdItem"/>
      <element type="rb:Codigo" name="Codigo"/>
      <element type="rb:CNPJ" name="CNPJOrigem"/>
      <element type="rb:CNPJ" name="CNPJTransportadora"/>
      <element type="rb:CNPJ" name="CNPJDestino"/>
      <element type="string" name="NotaFiscal"/>
      <element type="integer" name="Timestamp"/>
      <element type="integer" name="Timezone"/>
      <element type="rb:Info" name="Info" minOccurs="0"/>
      <element type="rb:InfoCliente" name="InfoCliente" minOccurs="0"/>
    </sequence>
		<attribute type="string" name="id" use="required"/>
  </complexType>
  <complexType name="agregacaoType">
    <sequence>
      <element type="string" name="IdParent"/>
      <element type="rb:childrenType" name="Itens" maxOccurs="unbounded" minOccurs="1"/>
      <element type="integer" name="Timestamp"/>
      <element type="integer" name="Timezone"/>
      <element type="rb:Info" name="Info" minOccurs="0"/>
      <element type="rb:InfoCliente" name="InfoCliente" minOccurs="0"/>
    </sequence>
		<attribute type="string" name="id" use="required"/>
  </complexType>
  <complexType name="eventosType">
    <choice maxOccurs="unbounded" minOccurs="0">
      <annotation>
        <documentation>Ordem ascendente de timestamp</documentation>
      </annotation>
      <element type="rb:registroType" name="Registro"/>
      <element type="rb:agregacaoType" name="Agregacao"/>
      <element type="rb:movimentacaoType" name="Movimentacao"/>
      <element type="rb:ocorrenciaType" name="Ocorrencia"/>
      <element type="rb:cancelamentoType" name="Cancelamento"/>
    </choice>
  </complexType>
  <complexType name="registroType">
    <sequence>
      <element type="rb:itemType" name="Item"/>
      <element type="integer" name="Timestamp"/>
      <element type="integer" name="Timezone"/>
      <element type="rb:Info" name="Info" minOccurs="0"/>
      <element type="rb:InfoCliente" name="InfoCliente" minOccurs="0"/>
    </sequence>
		<attribute type="string" name="id" use="required"/>
  </complexType>
</schema>

=== jeanschmidt/staticsite/xsd/eventosTeste.xml
<?xml version="1.0" encoding="UTF-8"?>
<rb:Eventos xmlns="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:rb="http://www.rastreabilidadebrasil.com.br/RBTypes" xsi:schemaLocation="http://www.rastreabilidadebrasil.com.br/RBTypes http://www.rastreabilidadebrasil.com.br/xsd/rb.xsd">
<!-- Eventos devem ser enviados em ordem CRESCENTE de TIMESTAMP -->
    <rb:Registro id="1">
        <rb:Item>
            <rb:GTIN>12345678901234</rb:GTIN>
            <rb:RegistroAnvisa>1234567890123</rb:RegistroAnvisa>
            <rb:Serial>0000000000001</rb:Serial>
            <rb:Lote>12345678901234</rb:Lote>
            <rb:DataValidade>1016</rb:DataValidade>
        </rb:Item>
        <rb:Timestamp>1404828300</rb:Timestamp> <!-- em segundos (unix timestamp) -->
        <rb:Timezone>-3</rb:Timezone>
        <rb:Info>Opcional</rb:Info>
        <rb:InfoCliente>Opcional</rb:InfoCliente>
    </rb:Registro>
    <rb:Registro id="2">
        <rb:Item>
            <rb:GTIN>12345678901234</rb:GTIN>
            <rb:RegistroAnvisa>1234567890123</rb:RegistroAnvisa>
            <rb:Serial>0000000000002</rb:Serial>
            <rb:Lote>12345678901234</rb:Lote>
            <rb:DataValidade>1016</rb:DataValidade>
        </rb:Item>
        <rb:Timestamp>1404828301</rb:Timestamp>
        <rb:Timezone>-3</rb:Timezone>
    </rb:Registro>
    <rb:Ocorrencia id="3">
        <rb:IdItem>12345678901230000000000001101612345678901234</rb:IdItem>
        <rb:Codigo>1010</rb:Codigo>
        <rb:Timestamp>1404828302</rb:Timestamp>
        <rb:Timezone>-3</rb:Timezone>
	<rb:Latitude>0.0</rb:Latitude><!—opcional—>
	<rb:Longitude>0.0<rb:Longitude><!—opcional—>
        <rb:Info>Info Opcional</rb:Info>
        <rb:InfoCliente>Info cliente Opcional</rb:InfoCliente>
    </rb:Ocorrencia>
    <rb:Ocorrencia id="4">
        <rb:IdItem>12345678901230000000000001101612345678901234</rb:IdItem>
        <rb:Codigo>1011</rb:Codigo>
        <rb:Timestamp>1404828303</rb:Timestamp>
        <rb:Timezone>-3</rb:Timezone>
    </rb:Ocorrencia>
    <rb:Ocorrencia id="5">
        <rb:IdItem>12345678901230000000000002101612345678901234</rb:IdItem>
        <rb:Codigo>1010</rb:Codigo>
        <rb:Timestamp>1404828304</rb:Timestamp>
        <rb:Timezone>-3</rb:Timezone>
    </rb:Ocorrencia>
    <rb:Ocorrencia id="6">
        <rb:IdItem>12345678901230000000000002101612345678901234</rb:IdItem>
        <rb:Codigo>1011</rb:Codigo>
        <rb:Timestamp>1404828305</rb:Timestamp>
        <rb:Timezone>-3</rb:Timezone>
    </rb:Ocorrencia>
	<rb:Agregacao id="7">
        <rb:IdParent>999999999999999999</rb:IdParent>
            <rb:Itens>
                <rb:IdItem>12345678901230000000000001101612345678901234</rb:IdItem>
                <rb:IdItem>12345678901230000000000002101612345678901234</rb:IdItem>
            </rb:Itens>
        <rb:Timestamp>1404828306</rb:Timestamp>
        <rb:Timezone>-3</rb:Timezone>
        <rb:Info>Info Opcional</rb:Info>
        <rb:InfoCliente>Info cliente Opcional</rb:InfoCliente>
    </rb:Agregacao>
    <rb:Movimentacao id="8">
        <rb:IdItem>999999999999999999</rb:IdItem>
        <rb:Codigo>2014</rb:Codigo> <!-- Exemplo de checkout (saida) -->
        <rb:CNPJOrigem>40942461000106</rb:CNPJOrigem><!-- Sem pontos e tracos -->
        <rb:CNPJTransportadora>57549437000104</rb:CNPJTransportadora><!-- Sem pontos e tracos -->
        <rb:CNPJDestino>36756394000150</rb:CNPJDestino><!-- Sem pontos e tracos -->
        <rb:NotaFiscal>1409656544246215410001061451</rb:NotaFiscal> <!-- Obrigatorio na movimentacao -->
        <rb:Timestamp>1404828310</rb:Timestamp>
        <rb:Timezone>-3</rb:Timezone>
        <rb:Info>Info Opcional</rb:Info>
        <rb:InfoCliente>Info cliente Opcional</rb:InfoCliente>
    </rb:Movimentacao>
    <rb:Movimentacao id="9">
        <rb:IdItem>999999999999999999</rb:IdItem>
        <rb:Codigo>2015</rb:Codigo> <!-- Exemplo de checkin (entrada) -->
        <rb:CNPJOrigem>36756394000150</rb:CNPJOrigem><!-- Sem pontos e tracos -->
        <rb:CNPJTransportadora>57549437000104</rb:CNPJTransportadora><!-- Sem pontos e tracos -->
        <rb:CNPJDestino>40942461000106</rb:CNPJDestino><!-- Sem pontos e tracos -->
        <rb:NotaFiscal>1409656544246215410001061451</rb:NotaFiscal> <!-- Obrigatorio na movimentacao -->
        <rb:Timestamp>1404828500</rb:Timestamp>
        <rb:Timezone>-3</rb:Timezone>
        <rb:Info>Info Opcional</rb:Info>
        <rb:InfoCliente>Info cliente Opcional</rb:InfoCliente>
    </rb:Movimentacao>
    <rb:Cancelamento id="10">
        <rb:IdItem>999999999999999999</rb:IdItem>
        <rb:Codigo>2015</rb:Codigo>
        <rb:Timestamp>1404828510</rb:Timestamp>
        <rb:Timezone>-3</rb:Timezone>
        <rb:Info>Info Opcional</rb:Info>
        <rb:InfoCliente>Info cliente Opcional</rb:InfoCliente>
    </rb:Cancelamento>
</rb:Eventos>
